export const SMS_CAMPAIGN_PLAN_TYPE = "sms_campaign";
export const SMS_CAMPAIGN_1700_STRIPE_PRICE_ID = "price_1TLsGLCxZc7GK7QKAKTBEXzF";
export const SMS_CAMPAIGN_1000_STRIPE_PRICE_ID = "price_1TOk5pCxZc7GK7QKlvKNFyuN";
export const SMS_CAMPAIGN_STRIPE_PRICE_IDS = [
  SMS_CAMPAIGN_1700_STRIPE_PRICE_ID,
  SMS_CAMPAIGN_1000_STRIPE_PRICE_ID
];

// Backward-compatible default for legacy imports.
export const SMS_CAMPAIGN_STRIPE_PRICE_ID = SMS_CAMPAIGN_1700_STRIPE_PRICE_ID;
